# Generated by Django 4.1.4 on 2023-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='duration',
            field=models.DateField(),
        ),
    ]
